enc = comm.LDPCEncoder(H);
dec = comm.LDPCDecoder('ParityCheckMatrix', H, ...
                       'DecisionMethod', 'Hard decision', ...
                       'IterationTerminationCondition', 'Parity check satisfied');